### ISSUE TITLE
Variabelen

### ISSUE THREAD

**Issue by Mokerstier** [lennartdeknikker/web-app-from-scratch-1920#3]
De link die je hier gebruikt om de api call te maken zou ik in een variabele stoppen ziet er iets netter uit.

https://github.com/lennartdeknikker/web-app-from-scratch-1920/blob/8da7eebd86d298ac257910a0e9953afbbe6da9a6/docs/js/app.js#L7

**Comment by lennartdeknikker** [comment]
url en headers zijn nu ondergebracht in aparte variabelen
```js
  // endpoint and request header configuration
  const endpoint = 'https://api.spacexdata.com/v3/';
  const requestOptions = {
    method: 'GET',
    redirect: 'follow'
  };
  ```
