### ISSUE TITLE
Breakup function in separate functions

### ISSUE THREAD

**Issue by joostf** [lennartdeknikker/web-app-from-scratch-1920#5]
https://github.com/lennartdeknikker/web-app-from-scratch-1920/blob/cc0fe391d400bdc345839beb8ad68ae0835cd351/docs/js/app.js#L9-L68

...with a clear single action for each function

**Comment by lennartdeknikker** [comment]
I broke down my code into various different actors and components returning objects with clear single action methods. Check out the actor and interaction diagram in the readme for the renewed structure.
