### ISSUE TITLE
Your naming convention is a bit verbose

### ISSUE THREAD

**Issue by joostf** [lennartdeknikker/web-app-from-scratch-1920#6]
Leaner naming of identifiers would make your code more readable

for example:
getDataFor -> getData

function renderElements(parentElement, childElementType, dataToShow) -> function render(parent, nodeType, data)

relevantData -> mission

You're code style is quit nice, with a leaner naming convention it could be even better!

**Comment by lennartdeknikker** [comment]
By restructuring my files and functions as methods on different actors, I changed the function names to be more accurate as well.
